import sys
sys.stdout.reconfigure(encoding='utf-8')

# Build the complete SocialPage.ets content
parts = []
parts.append("import { ApiService } from '../services/ApiService'")
parts.append("import { DatabaseHelper } from '../model/DatabaseHelper'")
parts.append("import { SocialPost } from '../common/Types'")
parts.append("import { SocialPostCard } from '../components/SocialPostCard'")
parts.append("import { EmptyState } from '../components/EmptyState'")
parts.append("import { Debouncer } from '../utils/Debouncer'")
parts.append("import { promptAction } from '@kit.ArkUI'")
parts.append("")
parts.append("@Component")
parts.append("export struct SocialPage {")
parts.append("  @State posts: SocialPost[] = []")
parts.append("  @State isLoading: boolean = false")
parts.append("  @State isCheckedIn: boolean = false")
parts.append("  @State consecutiveDays: number = 0")
parts.append("  @State inputText: string = ''")
parts.append("  @State currentPage: number = 1")
parts.append("  @State hasMore: boolean = true")
parts.append("")
parts.append("  private api: ApiService = ApiService.getInstance()")
parts.append("  private dbHelper: DatabaseHelper = DatabaseHelper.getInstance()")
parts.append("  private likeDebouncer: Debouncer = new Debouncer(500)")
parts.append("")
parts.append("  async aboutToAppear(): Promise<void> {")
parts.append("    await this.loadCheckinStatus()")
parts.append("    await this.loadPosts()")
parts.append("  }")
parts.append("")
parts.append("  async loadCheckinStatus(): Promise<void> {")
parts.append("    try {")
parts.append("      this.isCheckedIn = await this.dbHelper.isCheckedInToday()")
parts.append("      this.consecutiveDays = await this.dbHelper.getConsecutiveCheckinDays()")
parts.append("    } catch (err) {")
parts.append("      console.error('SocialPage', '加载打卡状态失败')")
parts.append("    }")
parts.append("  }")
parts.append("")
parts.append("  async doCheckin(): Promise<void> {")
parts.append("    try {")
parts.append("      const success = await this.dbHelper.doCheckin('', this.inputText)")
parts.append("      if (success) {")
parts.append("        this.isCheckedIn = true")
parts.append("        this.consecutiveDays = await this.dbHelper.getConsecutiveCheckinDays()")
parts.append("        promptAction.showToast({ message: '打卡成功！', duration: 1500 })")
parts.append("      }")
parts.append("    } catch (err) {")
parts.append("      promptAction.showToast({ message: '打卡失败，请重试', duration: 1500 })")
parts.append("    }")
parts.append("  }")
parts.append("")
parts.append("  async loadPosts(reset: boolean = true): Promise<void> {")
parts.append("    if (this.isLoading) return")
parts.append("    if (!reset && !this.hasMore) return")
parts.append("    this.isLoading = true")
parts.append("    if (reset) {")
parts.append("      this.currentPage = 1")
parts.append("      this.hasMore = true")
parts.append("    }")
parts.append("    try {")
parts.append("      const res = await this.api.getSocialPosts(this.currentPage, 10)")
parts.append("      if (res.code === 0 && res.data) {")
parts.append("        if (reset) {")
parts.append("          this.posts = res.data.list.map((item: SocialPost) => new SocialPost(")
parts.append("            item.id, item.content, item.likes, item.isLiked, item.createTime")
parts.append("          ))")
parts.append("        } else {")
parts.append("          this.posts = this.posts.concat(res.data.list.map((item: SocialPost) => new SocialPost(")
parts.append("            item.id, item.content, item.likes, item.isLiked, item.createTime")
parts.append("          )))")
parts.append("        }")
parts.append("        this.hasMore = res.data.list.length >= 10")
parts.append("        if (res.data.list.length > 0) {")
parts.append("          this.currentPage++")
parts.append("        }")
parts.append("      } else {")
parts.append("        if (this.posts.length === 0) {")
parts.append("          this.posts = this.getMockPosts()")
parts.append("        }")
parts.append("      }")
parts.append("    } catch (err) {")
parts.append("      if (this.posts.length === 0) {")
parts.append("        this.posts = this.getMockPosts()")
parts.append("      }")
parts.append("      promptAction.showToast({ message: '网络异常，已加载本地数据', duration: 2000 })")
parts.append("    } finally {")
parts.append("      this.isLoading = false")
parts.append("    }")
parts.append("  }")
parts.append("")
parts.append("  getMockPosts(): SocialPost[] {")
parts.append("    return [")
parts.append("      new SocialPost(1, '今天读了李白的《静夜思》，'举头望明月，低头思故乡'写得真好啊！', 12, false, '2026-06-11 10:30'),")
parts.append("      new SocialPost(2, '推荐大家读一读苏轼的《水调歌头》，每次读都有不同的感受。', 8, true, '2026-06-10 15:20'),")
parts.append("      new SocialPost(3, '白居易的《琵琶行》太长了，但写得确实精彩，'大弦嘈嘈如急雨，小弦切切如私语'', 5, false, '2026-06-10 09:15'),")
parts.append("      new SocialPost(4, '有没有人喜欢辛弃疾的词？'醉里挑灯看剑，梦回吹角连营'，豪放派的代表！', 15, false, '2026-06-09 20:00'),")
parts.append("      new SocialPost(5, '杜牧的《清明》'清明时节雨纷纷'，每年清明都会想起这首诗。', 3, false, '2026-06-09 14:50'),")
parts.append("      new SocialPost(6, '王维的诗画一体，'大漠孤烟直，长河落日圆'，画面感太强了！', 20, false, '2026-06-08 11:00'),")
parts.append("      new SocialPost(7, '孟浩然的《春晓》，简单几句就把春天早晨的美景写活了~', 7, false, '2026-06-07 16:30')")
parts.append("    ]")
parts.append("  }")
parts.append("")
parts.append("  onToggleLike(post: SocialPost): void {")
parts.append("    this.likeDebouncer.run(async () => {")
parts.append("      try {")
parts.append("        if (post.isLiked) {")
parts.append("          await this.api.unlikePost(post.id)")
parts.append("          post.likes--")
parts.append("        } else {")
parts.append("          await this.api.likePost(post.id)")
parts.append("          post.likes++")
parts.append("        }")
parts.append("        post.isLiked = !post.isLiked")
parts.append("      } catch (err) {")
parts.append("        post.likes += post.isLiked ? -1 : 1")
parts.append("        post.isLiked = !post.isLiked")
parts.append("      }")
parts.append("    })")
parts.append("  }")
parts.append("")
parts.append("  async publish(): Promise<void> {")
parts.append("    const text = this.inputText.trim()")
parts.append("    if (!text) return")
parts.append("    try {")
parts.append("      const res = await this.api.publishPost(text)")
parts.append("      if (res.code === 0 && res.data) {")
parts.append("        this.posts.unshift(res.data)")
parts.append("        promptAction.showToast({ message: '发布成功', duration: 1500 })")
parts.append("      }")
parts.append("    } catch (err) {")
parts.append("      this.posts.unshift({ id: Date.now(), content: text, likes: 0, isLiked: false, createTime: new Date().toLocaleString() })")
parts.append("    }")
parts.append("    this.inputText = ''")
parts.append("  }")
parts.append("")
parts.append("  build() {")
parts.append("    Column() {")
parts.append("      this.headerBar()")
parts.append("      this.checkinBar()")
parts.append("      if (this.posts.length === 0 && !this.isLoading) {")
parts.append("        EmptyState({")
parts.append("          icon: '\U0001F4AC',")
parts.append("          title: '暂无打卡动态',")
parts.append("          subtitle: '成为第一个打卡分享诗词感悟的人吧~',")
parts.append("          showRetry: false")
parts.append("        }).layoutWeight(1)")
parts.append("      } else {")
parts.append("        List({ space: 8 }) {")
parts.append("          ForEach(this.posts, (post: SocialPost) => {")
parts.append("            ListItem() {")
parts.append("              SocialPostCard({")
parts.append("                post: post,")
parts.append("                showDivider: true,")
parts.append("                onLikeClick: (p: SocialPost) => { this.onToggleLike(p) }")
parts.append("              })")
parts.append("            }")
parts.append("          }, (post: SocialPost) => post.id.toString())")
parts.append("        }")
parts.append("        .width('100%')")
parts.append("        .layoutWeight(1)")
parts.append("        .padding({ left: 12, right: 12, top: 8 })")
parts.append("        .scrollBar(BarState.Off)")
parts.append("        .onReachEnd(() => { this.loadPosts(false) })")
parts.append("      }")
parts.append("    }")
parts.append("    .width('100%')")
parts.append("    .height('100%')")
parts.append("    .backgroundColor('#F5F5F5')")
parts.append("  }")
parts.append("")
parts.append("  @Builder")
parts.append("  headerBar() {")
parts.append("    Row() {")
parts.append("      Text('打卡圈')")
parts.append("        .fontSize(20)")
parts.append("        .fontWeight(FontWeight.Bold)")
parts.append("        .fontColor('#333333')")
parts.append("    }")
parts.append("    .width('100%')")
parts.append("    .height(48)")
parts.append("    .padding({ left: 16, right: 16 })")
parts.append("    .backgroundColor('#FFFFFF')")
parts.append("  }")
parts.append("")
parts.append("  @Builder")
parts.append("  checkinBar() {")
parts.append("    Column() {")
parts.append("      Row() {")
parts.append("        Text('\U0001F4C5').fontSize(20)")
parts.append("        Blank().width(8)")
parts.append("        Column() {")
parts.append("          if (this.isCheckedIn) {")
parts.append("            Text('今日已打卡')")
parts.append("              .fontSize(14).fontColor('#7ED321').fontWeight(FontWeight.Medium)")
parts.append("          } else {")
parts.append("            Text('今日未打卡')")
parts.append("              .fontSize(14).fontColor('#999999').fontWeight(FontWeight.Medium)")
parts.append("          }")
parts.append("          Text('连续打卡 ' + this.consecutiveDays + ' 天')")
parts.append("            .fontSize(11).fontColor('#F5A623')")
parts.append("        }")
parts.append("        .alignItems(HorizontalAlign.Start).layoutWeight(1)")
parts.append("        if (!this.isCheckedIn) {")
parts.append("          Button('签到打卡')")
parts.append("            .fontSize(13).fontColor('#FFFFFF').backgroundColor('#4A90D9')")
parts.append("            .borderRadius(16).height(34).padding({ left: 16, right: 16 })")
parts.append("            .onClick(() => { this.doCheckin() })")
parts.append("        } else {")
parts.append("          Text('\u2713').fontSize(22).fontColor('#7ED321')")
parts.append("        }")
parts.append("      }")
parts.append("      .width('100%')")
parts.append("      .padding({ left: 16, right: 16, top: 12, bottom: 12 })")
parts.append("      if (!this.isCheckedIn) {")
parts.append("        Row() {")
parts.append("          TextInput({ placeholder: '今天读了哪首诗词？分享感悟...', text: this.inputText })")
parts.append("            .fontSize(13).backgroundColor('#F5F5F5').borderRadius(16).height(36)")
parts.append("            .layoutWeight(1).padding({ left: 12, right: 12 }).maxLength(200)")
parts.append("            .onChange((value: string) => { this.inputText = value })")
parts.append("        }")
parts.append("        .width('100%')")
parts.append("        .padding({ left: 16, right: 16, top: 0, bottom: 12 })")
parts.append("      }")
parts.append("    }")
parts.append("    .width('100%')")
parts.append("    .backgroundColor('#FFFFFF')")
parts.append("  }")
parts.append("}")

content = '\n'.join(parts) + '\n'
path = 'E:/CodeProjects/HarmonyOSProjects/WebApp/poemstudy/poemstudyapp/entry/src/main/ets/pages/SocialPage.ets'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(parts)} lines, {len(content)} bytes')
